### ISSUE TITLE
Set up a Kanban board for the group project

### ISSUE THREAD

**Issue by JonahKayizzi** [JonahKayizzi/space-travellers-hub#25]
This is the project [link](https://github.com/users/JonahKayizzi/projects/4) to the Kanban for the group project.

This project has two collaborators @normainobary2021  & @JonahKayizzi

**Comment by JonahKayizzi** [comment]
The project has been updated with an In Review column.

**Comment by brytebee** [comment]
Hi, Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
